juil. 15, 2017 7:52:21 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005017958',
'810005017958',
'',
'',
'RICARD-MURATORE'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:52:27 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000128545',
'810000128545',
'',
'',
'SANTI CANDERO',
...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:52:33 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001798247',
'810001798247',
'DR',
'Docteur',
'FAUVEAU...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:52:41 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000287713',
'810000287713',
'',
'',
'MAILLOT',
'MARIE...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:52:45 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549680',
'810002549680',
'DR',
'Docteur',
'PAUMARD...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:52:53 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10100619765',
'810100619765',
'DR',
'Docteur',
'DEMOOR'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:00 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001407963',
'810001407963',
'DR',
'Docteur',
'BOUVRAI...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:05 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549946',
'810002549946',
'DR',
'Docteur',
'BONTE',...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:19 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002550084',
'810002550084',
'DR',
'Docteur',
'BENOIT'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:30 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001590735',
'810001590735',
'DR',
'Docteur',
'PINEAU'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:39 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005827182',
'810005827182',
'',
'',
'DUPONT',
'BENJAM...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:53:47 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549698',
'810002549698',
'DR',
'Docteur',
'MEGRET'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:54:09 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002640869',
'810002640869',
'DR',
'Docteur',
'ECHEVER...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:54:32 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005716450',
'810005716450',
'',
'',
'BRUNEAU',
'ANNE-...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:54:45 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000036268',
'810000036268',
'DR',
'Docteur',
'MENIER'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:54:49 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001802031',
'810001802031',
'DR',
'Docteur',
'FROTTIN...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:55:02 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002537503',
'810002537503',
'DR',
'Docteur',
'LE ROLL...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:55:16 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:70) Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:137)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:211)
Caused by: java.sql.SQLDataException: (conn:70) Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005028013',
'810005028013',
'',
'',
'MONCIATTI',
'AUD...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:59:27 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR A...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005017958',
'810005017958',
'',
'',
'RICARD-MURATORE'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:59:33 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x85' for column 'Complement_destinataire' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000128545',
'810000128545',
'',
'',
'SANTI CANDERO',
...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:59:40 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001798247',
'810001798247',
'DR',
'Docteur',
'FAUVEAU...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:59:48 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR D...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000287713',
'810000287713',
'',
'',
'MAILLOT',
'MARIE...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 7:59:52 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549680',
'810002549680',
'DR',
'Docteur',
'PAUMARD...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:00 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92URG' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10100619765',
'810100619765',
'DR',
'Docteur',
'DEMOOR'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:06 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x9CUC S...' for column 'Mention_distribution' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001407963',
'810001407963',
'DR',
'Docteur',
'BOUVRAI...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:11 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549946',
'810002549946',
'DR',
'Docteur',
'BONTE',...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:24 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002550084',
'810002550084',
'DR',
'Docteur',
'BENOIT'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:35 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x8CUR D...' for column 'Bureau_cedex' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001590735',
'810001590735',
'DR',
'Docteur',
'PINEAU'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:44 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACTI...' for column 'Complement_destinataire' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005827182',
'810005827182',
'',
'',
'DUPONT',
'BENJAM...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:00:53 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002549698',
'810002549698',
'DR',
'Docteur',
'MEGRET'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:01:15 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002640869',
'810002640869',
'DR',
'Docteur',
'ECHEVER...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:01:38 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ARC' for column 'Libelle_Voie' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005716450',
'810005716450',
'',
'',
'BRUNEAU',
'ANNE-...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:01:52 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10000036268',
'810000036268',
'DR',
'Docteur',
'MENIER'...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:01:55 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92AVEN...' for column 'Complement_point_geographique' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10001802031',
'810001802031',
'DR',
'Docteur',
'FROTTIN...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:02:08 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ACCU...' for column 'Raison_sociale_site' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10002537503',
'810002537503',
'DR',
'Docteur',
'LE ROLL...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

juil. 15, 2017 8:02:22 PM com.ht.dev.rppsimport.DataBase batchExec
GRAVE: null
java.sql.BatchUpdateException: (conn:71) Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:318)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatch(MariaDbStatement.java:1278)
	at com.ht.dev.rppsimport.DataBase.batchExec(DataBase.java:135)
	at com.ht.dev.rppsimport.RppsImport.<init>(RppsImport.java:138)
	at com.ht.dev.rppsimport.RppsImport.main(RppsImport.java:214)
Caused by: java.sql.SQLDataException: (conn:71) Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeLargeBatchExceptionEpilogue(MariaDbStatement.java:315)
	... 4 more
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x92ANCI...' for column 'Libelle_Voie' at row 1
Query is: INSERT INTO `rpps`.`rpps`
(`Type_d_identifiant_PP`,
`Identifiant_PP`,
`Identification_nationale_PP`,
`Code_civilite_exercice`,
`Libelle_civilite_exercice`,
`Nom_d_exercice`,
`Prenom_d_exercice`,
`Code_profession`,
`Libelle_profession`,
`Code_categorie_professionnelle`,
`Libelle_categorie_professionnelle`,
`Code_savoir_faire`,
`Libelle_savoir_faire`,
`Code_type_savoir_faire`,
`Libelle_type_savoir_faire`,
`Numero_SIRET_site`,
`Numero_SIREN_site`,
`Numero_FINESS_site`,
`Numero_FINESS_etablissement_juridique`,
`Raison_sociale_site`,
`Enseigne_commerciale_site`,
`Identifiant_structure`,
`Complement_destinataire`,
`Complement_point_geographique`,
`Numero_Voie`,
`Indice_repetition_voie`,
`Code_type_de_voie`,
`Libelle_type_de_voie`,
`Libelle_Voie`,
`Mention_distribution`,
`Bureau_cedex`,
`Code_postal`,
`Code_commune`,
`Libelle_commune`,
`Code_pays`,
`Libelle_pays`,
`Telephone`,
`Telephone_2`,
`Telecopie`,
`Adresse_e_mail`,
`Adresse_BAL_MSSante`)
VALUES
('8',
'10005028013',
'810005028013',
'',
'',
'MONCIATTI',
'AUD...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:394)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:139)
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

